library(tidyverse)

#to read in a single CSV generated by Passime, use this code

clusters <- as_data_frame(read.csv(file="./data/FILENAME.csv")[ , c("cluster", "date", "title")]) %>% 
  mutate(title = gsub('(.*)\\.*\\(.*','\\1',title)) %>%
  mutate(date = as.Date(date, "%Y-%m-%d"))

# to read in multiple CSVs generated by Passim, use this code. Note that Passim's CSV files can be quite large, and this is unlikely to work if pointed to a folder with the full output of a Passim run. I tend to test with 5-10 CSVs at a time.
files <- dir(path = "./data", pattern = '*.csv', full.names = TRUE)

clusters <- do.call(rbind, lapply(files, read_csv)) %>%
  select(cluster, date, title) %>%
  mutate(title = gsub('(.*)\\.*\\(.*','\\1',title)) %>%
  mutate(date = as.Date(date, "%Y-%m-%d"))
  
# this relatively simple code joins the table to itself, creating a line for each potential edge within a cluster. It then filters those matches so that the output includes only those lines in which the second date follows the first, as network edges cannot generally point backwards in time.
directed <- full_join(clusters, clusters, by = "cluster") %>%
  filter(date.x < date.y)

View(directed)

# write edges to a CSV for use in Gephi or other network visualization software

write.csv(directed, file="./output/FILENAME.csv")
